require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop/require_tools
  - rubocop-packaging

AllCops:
  NewCops: enable

Layout/FirstHashElementIndentation:
  Exclude:
    - 'lib/dx/api/search.rb'
